---
- name: Programming
  hosts: localhost
  roles:
  - role: common
  - role: programming
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    ruby_version: 3.3
    golang_version: 1.21
    node_version: 20
    java_version: 21