---
- name: Install with mise
  ansible.builtin.shell: |
    {{ home_directory }}/.local/bin/mise use -g {{ name }}@{{ version }} --yes
  vars:
    name: ""
    version: ""
  tags:
  - ubuntu
  - macos
