programming:
  apt_packages:
  - jq
  - make
  - remmina
  # Warp
  - libxkbcommon-x11-0
  - libegl1

  apt_additional_packages:
  - name: sublimetext
    gpg_key: https://download.sublimetext.com/sublimehq-pub.gpg
    apt_repo: https://download.sublimetext.com/ 
    release: apt/stable/
    packages:
    - sublime-text
  - name: vscode
    gpg_key: https://packages.microsoft.com/keys/microsoft.asc
    apt_repo: https://packages.microsoft.com/repos/vscode
    release: "stable main"
    packages:
    - code

  install_deb:
  - name: warp
    url: "https://app.warp.dev/download?package=deb"

  install_scripts:
  - name: node
    url: https://deb.nodesource.com/setup_{{ node_version }}.x
    post_script: "apt-get install -y nodejs"

  ppa_packages:
  - name: rvm
    repo: rael-gc/rvm
    packages:
    - rvm

  add_user_to_groups:
  - rvm