programming:
  apt_packages:
  - zsh
  - jq
  - make
  - remmina
  # Warp
  - libxkbcommon-x11-0
  - libegl1
  # Ruby
  - libffi-dev
  - libyaml-dev

  apt_additional_packages:
  - name: sublimetext
    gpg_key: https://download.sublimetext.com/sublimehq-pub.gpg
    apt_repo: https://download.sublimetext.com/ 
    release: apt/stable/
    packages:
    - sublime-text
  - name: vscode
    gpg_key: https://packages.microsoft.com/keys/microsoft.asc
    apt_repo: https://packages.microsoft.com/repos/vscode
    release: "stable main"
    packages:
    - code

  install_deb:
  - name: warp
    url: "https://app.warp.dev/download?package=deb"

  install_scripts:
  - name: mise
    url: https://mise.run
    post_script: "mv /root/.local/bin/mise /home/{{ ansible_user_id }}/.local/bin && echo 'eval \"$(/home/{{ ansible_user_id }}/.local/bin/mise activate bash)\"' >> /home/{{ ansible_user_id }}/.bashrc && echo 'eval \"$(/home/{{ ansible_user_id }}/.local/bin/mise activate zsh)\"' >> /home/{{ ansible_user_id }}/.zshrc"
