---
- name: Install
  include_tasks:
    file: tasks/install.yml
  vars: 
    apt_packages: "{{ programming.apt_packages }}"
    apt_additional_packages: "{{ programming.apt_additional_packages }}"
    install_deb: "{{ programming.install_deb }}"
    install_scripts: "{{ programming.install_scripts }}"
  tags:
  - ubuntu

- name: Install Go
  ansible.builtin.shell: |
    /home/{{ ansible_user_id }}/.local/bin/mise use -g go@{{ golang_version }}
  tags:
  - ubuntu

- name: Install NodeJS
  ansible.builtin.shell: |
    /home/{{ ansible_user_id }}/.local/bin/mise use -g node@{{ node_version }}
  tags:
  - ubuntu

- name: Install Java
  ansible.builtin.shell: |
    /home/{{ ansible_user_id }}/.local/bin/mise use -g java@{{ java_version }}
  tags:
  - ubuntu

- name: Install Ruby
  ansible.builtin.shell: |
    /home/{{ ansible_user_id }}/.local/bin/mise use -g ruby@{{ ruby_version }}
  tags:
  - ubuntu
