---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  become: true
  tags:
  - ubuntu
  
- name: Install
  include_tasks:
    file: tasks/install.yml
  vars: 
    apt_packages: "{{ common.apt_packages }}"
  tags:
  - ubuntu