---
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  become: true
  tags:
  - ubuntu
  
- name: Install
  include_tasks:
    file: tasks/install.yml
  vars: 
    apt_packages: "{{ ubuntu.apt_packages }}"
  tags:
  - ubuntu

- name: Update all packages to their latest version
  ansible.builtin.shell: |
    brew update
    brew upgrade
  become: false
  tags:
  - macos

- name: Set home directory (Linux)
  ansible.builtin.set_fact:
    home_directory: /home/{{ ansible_user_id }}
  tags:
  - ubuntu

- name: Set home directory (MacOS)
  ansible.builtin.set_fact:
    home_directory: /Users/{{ ansible_user_id }}
  tags:
  - macos
