---
- name: Install docker
  include_tasks:
    file: tasks/install.yml
  vars: 
    apt_additional_packages:
    - name: docker
      gpg_key: https://download.docker.com/linux/ubuntu/gpg
      apt_repo: https://download.docker.com/linux/ubuntu
      release: "$(lsb_release -cs) stable"
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
  tags:
  - ubuntu

- name: Install docker (desktop)
  include_tasks:
    file: tasks/install_with_homebrew.yml
  vars: 
    name: "docker"
    cask: "--cask"
  tags:
  - macos
