---
- name: Install rand
  ansible.builtin.shell: |
    curl -fsSL -o rand-linux-amd64.zip https://github.com/nu12/rand/releases/download/{{ rand.version }}/rand-linux-amd64.zip
    unzip rand-linux-amd64.zip
    chmod +x rand
    mv rand /usr/bin/
    rm rand-linux-amd64.zip
  become: true
  tags:
  - ubuntu

- name: Install rand
  ansible.builtin.shell: |
    curl -fsSL -o rand-darwin-arm64.zip https://github.com/nu12/rand/releases/download/{{ rand.version }}/rand-darwin-arm64.zip
    unzip rand-darwin-arm64.zip
    chmod +x rand
    mv rand /Users/{{ ansible_user_id }}/.local/bin/
    rm rand-darwin-arm64.zip
  become: false
  tags:
  - macos
