---
- name: Set package name (Linux)
  ansible.builtin.set_fact:
    rand_package: rand-linux-amd64
  tags:
  - ubuntu

- name: Set package name (MacOS)
  ansible.builtin.set_fact:
    rand_package: rand-darwin-arm64
  tags:
  - macos

- name: Install rand
  ansible.builtin.shell: |
    curl -fsSL -o {{ rand_package }}.zip https://github.com/nu12/rand/releases/download/{{ rand.version }}/{{ rand_package }}.zip
    unzip {{ rand_package }}.zip
    chmod +x rand
    mv rand {{ home_directory }}/.local/bin/
    rm {{ rand_package }}.zip
  become: false
  tags:
  - ubuntu
  - macos
