---
- name: Install sublimetext
  include_tasks:
    file: tasks/install.yml
  vars: 
    apt_additional_packages:
    - name: sublimetext
      gpg_key: https://download.sublimetext.com/sublimehq-pub.gpg
      apt_repo: https://download.sublimetext.com/ 
      release: apt/stable/
      packages:
      - sublime-text
  tags:
  - ubuntu

- name: Install sublimetext
  include_tasks:
    file: tasks/install_with_homebrew.yml
  vars: 
    name: "sublime-text"
    cask: "--cask"
  tags:
  - macos
