---
- name: Install
  include_tasks:
    file: tasks/install.yml
  vars: 
    apt_packages: "{{ misc.apt_packages }}"
    apt_additional_packages: "{{ misc.apt_additional_packages }}"
    install_deb: "{{ misc.install_deb }}"
    install_binaries: "{{ misc.install_binaries }}"
  tags:
  - ubuntu
