name: Build
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  workflow_dispatch: {}

jobs:
  ubuntu:
    strategy:
      matrix:
        dockerfile: [ubuntu-24.04]
        playbook: [setup]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run playbook
      run: |
        PLATFORM=$(echo ${{ matrix.dockerfile }} | cut -d "-" -f 1)
        docker build -f .github/dockerfiles/${{ matrix.dockerfile }}.Dockerfile -t setup .
        docker run setup /bin/bash -c "/home/me/.local/bin/ansible-playbook ${{ matrix.playbook }}.yml --tags $PLATFORM"

  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install ansible
      run: |
        brew install ansible
    - name: Run playbook
      run: |
        ansible-playbook setup.yml --tags macos
